- README.md
> Update README.md - fixed broken link

- .github/workflows/releasing.yml
adding simple releasing workflow, just need to configure Pypi token :chipmunk:
> release workflow

- tests/___test_augmentations.py
fixing broken imports in tests
> fix tests/import

- docs/tutorials/09-Low-level API Usecases.ipynb
- docs/tutorials/10-Test Time Augmentation.ipynb
- src/pytorch_tabular/categorical_encoders.py
- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/ssl_models/base_model.py
- src/pytorch_tabular/ssl_models/common/layers.py
- src/pytorch_tabular/ssl_models/dae/dae.py
- src/pytorch_tabular/tabular_model.py
- src/pytorch_tabular/utils.py
- tests/test_common.py
added verbose option in evaluate, reset_model, and tutorials
> Reset_model, verbose evaluate, and tutorials

- docs/apidocs_common.md
- docs/apidocs_config.md
- docs/apidocs_coreclasses.md
- docs/apidocs_head.md
- docs/apidocs_model.md
- docs/apidocs_ssl.md
- docs/apidocs_utils.md
- docs/authors.md
- docs/contributing.md
- docs/data.md
- docs/development_manual.md
- docs/experiment_tracking.md
- docs/index.md
- docs/models.md
- docs/optimizer.md
- docs/other_features.md
- docs/tabular_model.md
- docs/training.md
- docs/tutorials/01-Basic_Usage.ipynb
- docs/tutorials/02-Advanced_Usage.ipynb
- docs/tutorials/03-Extracting and Using Learned Embeddings.ipynb
- docs/tutorials/04-Implementing New Architectures.ipynb
- docs/tutorials/05-Experiment_Tracking.ipynb
- docs/tutorials/06-Imbalanced Classification.ipynb
- docs/tutorials/07-Probabilistic Regression with MDN.ipynb
- docs/tutorials/08-Self-Supervised Learning-DAE.ipynb
- docs/tutorials/09-Low-level API Usecases.ipynb
- docs/tutorials/10-Test Time Augmentation.ipynb
- mkdocs.yml
- requirements_dev.txt
----
:books: Documentation preview :books:: https://pytorch-tabular--130.org.readthedocs.build/en/130/
> add pre-commit to dev req, docs update

- src/pytorch_tabular/categorical_encoders.py
- src/pytorch_tabular/feature_extractor.py
- src/pytorch_tabular/tabular_model.py
----
:books: Documentation preview :books:: https://pytorch-tabular--137.org.readthedocs.build/en/137/
> removed tqdm and switched over to rich

- src/pytorch_tabular/tabular_model.py
----
:books: Documentation preview :books:: https://pytorch-tabular--139.org.readthedocs.build/en/139/
> flag for predict df

- examples/__only_for_dev__/adhoc_scaffold.py
- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/models/gate/gate_model.py
- src/pytorch_tabular/models/node/node_model.py
- src/pytorch_tabular/tabular_model.py
Added GPU enabled predictions
Added early stopping kwargs
Added data aware init batch size
Added checkpoint kwargs
----
:books: Documentation preview :books:: https://pytorch-tabular--141.org.readthedocs.build/en/141/
> Add_parameters

- docs/history.md
- examples/__only_for_dev__/to_test_dae.py
- requirements.txt
- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/models/ft_transformer/config.py
- src/pytorch_tabular/models/tab_transformer/config.py
- src/pytorch_tabular/tabular_model.py
----
:books: Documentation preview :books:: https://pytorch-tabular--142.org.readthedocs.build/en/142/
> Updating Torchmetrics dependency

- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/tabular_model.py
----
:books: Documentation preview :books:: https://pytorch-tabular--146.org.readthedocs.build/en/146/
> default to multiclass accuracy

- README.md
- setup.cfg
my legal name :)
----
:books: Documentation preview :books:: https://pytorch-tabular--151.org.readthedocs.build/en/151/
> borda - Name

- requirements.txt
----
:books: Documentation preview :books:: https://pytorch-tabular--161.org.readthedocs.build/en/161/
> updated protobuf requrement

- requirements.txt
this shall simplify work of pip resolver
closes #177
----
:books: Documentation preview :books:: https://pytorch-tabular--188.org.readthedocs.build/en/188/
> req: replace * with range

- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/ssl_models/base_model.py
- src/pytorch_tabular/tabular_model.py
cc: @manujosephv
----
:books: Documentation preview :books:: https://pytorch-tabular--190.org.readthedocs.build/en/190/
> simplify keys / get

- .pre-commit-config.yaml
- README.md
cc: @manujosephv
----
:books: Documentation preview :books:: https://pytorch-tabular--193.org.readthedocs.build/en/193/
> enable mdformat

- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/tabular_model.py
Fixes #163 #164 
- added mps as an accelertor
- disabled rich progress bar when enable_progress_bar is False
----
:books: Documentation preview :books:: https://pytorch-tabular--209.org.readthedocs.build/en/209/
> Minor_bugfixes

- .pre-commit-config.yaml
- docs/tabular_model.md
- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/tabular_model.py
Dummy commits to trigger Doc Rebuild
----
:books: Documentation preview :books:: https://pytorch-tabular--226.org.readthedocs.build/en/226/
> pre=commit formatting

- src/pytorch_tabular/tabular_datamodule.py
Simplify long leaves in if/else branching by using return
----
:books: Documentation preview :books:: https://pytorch-tabular--295.org.readthedocs.build/en/295/
> refactor: simplify logic in datamodule

- .github/workflows/testing.yml
- tests/conftest.py
once the missing dataset is back online and properly cached this will prevent future eventual downtime... also this shall fail sooner in testing life-cycle
----
:books: Documentation preview :books:: https://pytorch-tabular--301.org.readthedocs.build/en/301/
> ci: cash tests dataset

- .gitignore
- tests/conftest.py
Switching from https to http to avoid certificate issue for UCI ML Repo
----
:books: Documentation preview :books:: https://pytorch-tabular--303.org.readthedocs.build/en/303/
> temporary fix for test cases

- src/pytorch_tabular/categorical_encoders.py
- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/tabular_datamodule.py
- src/pytorch_tabular/tabular_model.py
- src/pytorch_tabular/utils/data_utils.py
there is no need to import the whole package when only the class is used
----
:books: Documentation preview :books:: https://pytorch-tabular--307.org.readthedocs.build/en/307/
> simplify using `pandas`

- src/pytorch_tabular/tabular_model.py
----
:books: Documentation preview :books:: https://pytorch-tabular--317.org.readthedocs.build/en/317/
> fixing assert statement for metrics_prob_input

- .github/workflows/testing.yml
- requirements/base.txt
- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/models/mixture_density/mdn.py
- src/pytorch_tabular/models/tabnet/config.py
- src/pytorch_tabular/models/tabnet/tabnet_model.py
- src/pytorch_tabular/ssl_models/base_model.py
- src/pytorch_tabular/tabular_model.py
A PR to accomodate a few more changes and add on to @Borda PR #297
----
:books: Documentation preview :books:: https://pytorch-tabular--318.org.readthedocs.build/en/318/
> bump: pytorch-lightning >=2.0 & enable Torch 2.0+ (contd.)

- docs/tutorials/09-Low-level API Usecases(CV, Tuning, and more).ipynb
- src/pytorch_tabular/__init__.py
- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/tabular_model.py
- src/pytorch_tabular/tabular_model_tuner.py
- tests/test_common.py
This pull request introduces new features. Here is a summary of the changes:
- Added tabular tuner
- Added test cases
- Implemented verbose logging
----
📚 Documentation preview 📚: https://pytorch-tabular--340.org.readthedocs.build/en/340/
> Adds Hyperparameter Tuning

- src/pytorch_tabular/tabular_model.py
- src/pytorch_tabular/tabular_model_tuner.py
This Pr adds verbose mode to Tabular Model
----
📚 Documentation preview 📚: https://pytorch-tabular--341.org.readthedocs.build/en/341/
> Adds verbose mode

- src/pytorch_tabular/tabular_model.py
- tests/test_common.py
This Pr adds ability to bag predictions using a CV scheme
----
📚 Documentation preview 📚: https://pytorch-tabular--349.org.readthedocs.build/en/349/
> Adding Bagged Prediction

- src/pytorch_tabular/tabular_model.py
This PR adds some markets like is_fitted etc to tabular model and also modifies the summary method to behave in different ways depending on the state of the model
----
📚 Documentation preview 📚: https://pytorch-tabular--350.org.readthedocs.build/en/350/
> Add is_fitted and other markers to tabular model

- docs/tabular_model.md
- src/pytorch_tabular/categorical_encoders.py
- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/feature_extractor.py
- src/pytorch_tabular/models/autoint/autoint.py
- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/models/mixture_density/mdn.py
- src/pytorch_tabular/models/node/config.py
- src/pytorch_tabular/ssl_models/base_model.py
- src/pytorch_tabular/tabular_model.py
- src/pytorch_tabular/tabular_model_tuner.py
----
📚 Documentation preview 📚: https://pytorch-tabular--351.org.readthedocs.build/en/351/
> General_improvements and Doc changes

- src/pytorch_tabular/models/common/layers/activations.py
- src/pytorch_tabular/tabular_datamodule.py
- src/pytorch_tabular/tabular_model.py
----
📚 Documentation preview 📚: https://pytorch-tabular--353.org.readthedocs.build/en/353/
> verbosity fix for tabular datamodule

- src/pytorch_tabular/models/common/layers/activations.py
- src/pytorch_tabular/tabular_model.py
- src/pytorch_tabular/tabular_model_tuner.py
- src/pytorch_tabular/utils/__init__.py
- src/pytorch_tabular/utils/nn_utils.py
This PR adds handling of OOM cases gracefully and also makes the tuning robust to OOMs
----
📚 Documentation preview 📚: https://pytorch-tabular--354.org.readthedocs.build/en/354/
> added graceful OOM handling

- src/pytorch_tabular/tabular_datamodule.py
- src/pytorch_tabular/tabular_model.py
- src/pytorch_tabular/tabular_model_tuner.py
- tests/test_common.py
This PR adds test time augmentation to predict. This works by augmenting initial data set by adding noise and averaging while inferencing.
----
📚 Documentation preview 📚: https://pytorch-tabular--355.org.readthedocs.build/en/355/
> Test Time Augmentation and other bug fixes

- src/pytorch_tabular/tabular_model.py
- src/pytorch_tabular/tabular_model_tuner.py
This PR addas a flag to suppress logs generated by Pytorch Lightning
----
📚 Documentation preview 📚: https://pytorch-tabular--367.org.readthedocs.build/en/367/
> Flag to disable Lightning Logs

- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/models/common/heads/config.py
- src/pytorch_tabular/tabular_model.py
- src/pytorch_tabular/tabular_model_sweep.py
- Change default variable ("fast" no longer exists)
- Fix documentation structure
----
📚 Documentation preview 📚: https://pytorch-tabular--394.org.readthedocs.build/en/394/
> Fix documentation structure and change default variable

- src/pytorch_tabular/tabular_datamodule.py
Fixes https://github.com/manujosephv/pytorch_tabular/issues/404#issue-2147546679
Let me know if there is any changes I should make. 
----
📚 Documentation preview 📚: https://pytorch-tabular--420.org.readthedocs.build/en/420/
> TabularDataModule: Fix pandas returning a series when calling nunique()

- src/pytorch_tabular/categorical_encoders.py
- src/pytorch_tabular/tabular_datamodule.py
**Enhancement:**
- Fixed Value Error when categorical column is of dtype "Categorical".
**Fixes Issue:**
- Closes #79 .
----
📚 Documentation preview 📚: https://pytorch-tabular--493.org.readthedocs.build/en/493/
> Bug fix for "Categorical" dtype
