- examples/classification_with_NODE.ipynb
The `classificaiton_with_NODE` notebook is missing a few imports and had several redundant and unused imports. This PR adresses these.
Fixes #33
> Fixed missing imports in classification_with_NODE notebook

- .pre-commit-config.yaml
- src/pytorch_tabular/categorical_encoders.py
- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/models/common/layers.py
- src/pytorch_tabular/models/gate/components.py
- src/pytorch_tabular/ssl_models/common/layers.py
- src/pytorch_tabular/ssl_models/common/noise_generators.py
as py3.7 is set as min python version we can also enable this hook
cc: @manujosephv
----
:books: Documentation preview :books:: https://pytorch-tabular--192.org.readthedocs.build/en/192/
> enable pyupgrade for py3.7

- src/pytorch_tabular/models/gate/config.py
Changing default activation in GATE to sparsemax and sparsemoid for runtime optimization
----
:books: Documentation preview :books:: https://pytorch-tabular--196.org.readthedocs.build/en/196/
> changed GATE defaults to sparsemax

- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/models/ft_transformer/ft_transformer.py
- src/pytorch_tabular/models/gate/gate_model.py
- src/pytorch_tabular/tabular_model.py
Added new method in TabularModel and enabled feature importance for FTTransformer and GATE
----
:books: Documentation preview :books:: https://pytorch-tabular--220.org.readthedocs.build/en/220/
> Added Feature Importance

- src/pytorch_tabular/models/base_model.py
The misnamed metrics_prob_inputs in the code results in no way to use probability calculations in the metrics under the classification task. 
----
:books: Documentation preview :books:: https://pytorch-tabular--239.org.readthedocs.build/en/239/
> Fix metrics_prob_inputs naming error

- tests/test_autoint.py
- tests/test_categorical_embedding.py
- tests/test_datamodule.py
- tests/test_ft_transformer.py
- tests/test_gandalf.py
- tests/test_gate.py
- tests/test_mdn.py
- tests/test_node.py
- tests/test_ssl.py
- tests/test_tabnet.py
- tests/test_tabtransformer.py
the if/else fork is quite confusing so replacing it with simple `retun`
moreover, in most cases, there is not such configuration in test parametrization so it can be dropped completely
----
:books: Documentation preview :books:: https://pytorch-tabular--294.org.readthedocs.build/en/294/
> tests: prune meaningless `assert True`

- .github/workflows/label-conflicts.yml
to work it correctly, you need also to create such label `has conflicts`
the reason is that otherwise, it takes a few more steps/click to find out why a PR with all green was not merged yet, and if you have bunch of PRs open you gain a much better overview
----
:books: Documentation preview :books:: https://pytorch-tabular--293.org.readthedocs.build/en/293/
> ci: add action to label PR conflicts

- docs/data.md
Outdated argument names, but it probably would be good to have all API used in docs tested...
----
:books: Documentation preview :books:: https://pytorch-tabular--292.org.readthedocs.build/en/292/
> docs: fix args in DataConfig

- src/pytorch_tabular/tabular_datamodule.py
- src/pytorch_tabular/tabular_model.py
- src/pytorch_tabular/utils/nn_utils.py
there is some strange bug https://github.com/Lightning-AI/lightning/issues/18444#issuecomment-1807007492 with a torch, so this will allow us to bypass it
and also simplify too long `<var> if <var> is is not None else <var2>`
----
:books: Documentation preview :books:: https://pytorch-tabular--296.org.readthedocs.build/en/296/
> refactor: use seed and using or

- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/ssl_models/base_model.py
- src/pytorch_tabular/tabular_model.py
This simple extension allows the use of custom optimizer packages such as:
- https://pytorch-optimizers.readthedocs.io/en/latest/
- https://github.com/lucidrains/lion-pytorch
----
:books: Documentation preview :books:: https://pytorch-tabular--300.org.readthedocs.build/en/300/
> feat: allow custom optimizer

- .gitignore
- src/pytorch_tabular/ssl_models/dae/dae.py
Fixes #304 by making sure the bcewithcrossentropy is called with right data types
----
:books: Documentation preview :books:: https://pytorch-tabular--315.org.readthedocs.build/en/315/
> fixed bug for ssl with binary dtype

- .gitignore
- src/pytorch_tabular/tabular_datamodule.py
- src/pytorch_tabular/tabular_model.py
- tests/test_common.py
- tests/test_datamodule.py
When you train a model and later you want to use it for simple inference it is very convenient to use this symmetric functions `save_model` and `load_model`. But when trained on a large dataset the artifact is super large even if you won't ever need the train/vali/test datasets... 
So, this PR will allow the drop of the dataset's DataFrames and save DataModule without them.
----
:books: Documentation preview :books:: https://pytorch-tabular--312.org.readthedocs.build/en/312/
> feat: allow saving model without full dataset

- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/tabular_datamodule.py
- tests/test_datamodule.py
`infer_datetime_format=True` in `to_datetime` is deprecated since pandas 2.0.0 per https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html
this PR adds a new required `format` param to the `date_columns` list in config which is passed down to the `to_datetime` call inside of `TabularDatamodule.make_date`
----
:books: Documentation preview :books:: https://pytorch-tabular--329.org.readthedocs.build/en/329/
> require passing in `date_format` for `date_columns`

- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/models/category_embedding/category_embedding_model.py
- src/pytorch_tabular/models/common/layers/__init__.py
- src/pytorch_tabular/models/common/layers/batch_norm.py
- src/pytorch_tabular/models/common/layers/embeddings.py
- src/pytorch_tabular/models/common/layers/misc.py
- src/pytorch_tabular/models/ft_transformer/ft_transformer.py
- src/pytorch_tabular/models/gandalf/gandalf.py
- src/pytorch_tabular/models/gate/gate_model.py
- src/pytorch_tabular/models/node/node_model.py
- src/pytorch_tabular/models/tab_transformer/tab_transformer.py
- src/pytorch_tabular/ssl_models/common/layers.py
- src/pytorch_tabular/ssl_models/dae/dae.py
- src/pytorch_tabular/utils/nn_utils.py
- tests/test_categorical_embedding.py
This PR adds Ghost Batch Normalization as an alternative to BatchNorm in all architectures
----
📚 Documentation preview 📚: https://pytorch-tabular--346.org.readthedocs.build/en/346/
> Ghost Batch Normalization

- requirements/base.txt
- src/pytorch_tabular/models/common/layers/activations.py
This PR moves the dependency for entmax activations inside the repo for conda compatibility
----
📚 Documentation preview 📚: https://pytorch-tabular--352.org.readthedocs.build/en/352/
> Remove entmax dependency

- src/pytorch_tabular/tabular_model.py
- tests/test_common.py
----
📚 Documentation preview 📚: https://pytorch-tabular--356.org.readthedocs.build/en/356/
> Bug Fix in bagging_pred and TTA

- src/pytorch_tabular/tabular_datamodule.py
if new features are added in `tabular_datamodule.preprocess_data` we need to update `embedding_dims` again to account for the new features
nb @manujosephv: calling `_update_config` was the simplest way i could see to do this but let me know if you'd prefer something else
----
📚 Documentation preview 📚: https://pytorch-tabular--358.org.readthedocs.build/en/358/
> bugfix: update embedding_dims if new features are added

- docs/experiment_tracking.md
Fix syntax error in experiment_tracking.md log_target
----
📚 Documentation preview 📚: https://pytorch-tabular--382.org.readthedocs.build/en/382/
> Fix syntax error in experiment_tracking.md log_target

- src/pytorch_tabular/tabular_model_tuner.py
The Tuner is not changing the hyperparameters, like we can see in the following images. I changed the code to print the configs:
Was to change "layers" to "1-1-1", but before and after the current code is not changing the values. With the new code, it is changing. I do not know how it is not raising an exception because it is trying to change an attribute that does not exist.
----
📚 Documentation preview 📚: https://pytorch-tabular--384.org.readthedocs.build/en/384/
> Fix attr that was not been changed

- src/pytorch_tabular/tabular_model_sweep.py
Fixed bug when using model_sweep with "model_list" = "full" or "high_memory".
Fixed to show OOM models in output DataFrame.
----
📚 Documentation preview 📚: https://pytorch-tabular--383.org.readthedocs.build/en/383/
> Fix cannot pickle generator object error

- src/pytorch_tabular/config/config.py
#424 raised an issue regarding MDN heads. But the usages wasn't as intended. So adding protection against such usage
----
📚 Documentation preview 📚: https://pytorch-tabular--448.org.readthedocs.build/en/448/
> Protection for MDN Head misuse

- docs/models.md
----
📚 Documentation preview 📚: https://pytorch-tabular--455.org.readthedocs.build/en/455/
> Fixed typo in metrics_prob_input

- .github/workflows/releasing.yml
- requirements/base.txt
- requirements/dev.txt
resolving some compatibility issues:
`AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.`
coming from third-party dependencies
----
📚 Documentation preview 📚: https://pytorch-tabular--482.org.readthedocs.build/en/482/
> freeze `numpy <2.0` & fix ci+docs

- src/pytorch_tabular/tabular_model.py
I've simply removed the `if` block that prevented setting these to true in config for SSL models. I'm open to adding to documentation or test cases if needed. 
----
📚 Documentation preview 📚: https://pytorch-tabular--470.org.readthedocs.build/en/470/
> Remove restriction for using missing and unknown category in SSL models

- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/tabular_datamodule.py
**Modified Components:**
- `train_loader`, `val_loader`, and `prepare_inference_dataloader` in `src/pytorch_tabular/tabular_datamodule.py`
- `DataConfig` in `src/pytorch_tabular/config/config.py`
**Enhancement:**
- Added support for passing **kwargs to DataLoader for greater flexibility and customizability.
**Fixes Issue:**
- Closes #411.
----
📚 Documentation preview 📚: https://pytorch-tabular--492.org.readthedocs.build/en/492/
> Add dataloader_kwargs support in DataConfig

- .gitignore
- src/pytorch_tabular/tabular_model.py
- tests/test_common.py
Added informative str and repr methods.
Added an _repr_html_ for fancy display in notebooks
----
📚 Documentation preview 📚: https://pytorch-tabular--507.org.readthedocs.build/en/507/
> Adding informative str and repr 

- src/pytorch_tabular/tabular_datamodule.py
- src/pytorch_tabular/tabular_model.py
Adjust the preprocessing stage for training and validation data based on the SSL flag and streamline the configuration override for the datamodule.
Fix for issue #503
----
📚 Documentation preview 📚: https://pytorch-tabular--510.org.readthedocs.build/en/510/
> Fix SSL finetuning bug

- README.md
Replace the outdated link for the Denoising AutoEncoder tutorial with an updated one.
----
📚 Documentation preview 📚: https://pytorch-tabular--511.org.readthedocs.build/en/511/
> Update broken link for Denoising AutoEncoder tutorial

- src/pytorch_tabular/categorical_encoders.py
- src/pytorch_tabular/config/config.py
- src/pytorch_tabular/feature_extractor.py
- src/pytorch_tabular/models/base_model.py
- src/pytorch_tabular/ssl_models/base_model.py
- src/pytorch_tabular/ssl_models/dae/dae.py
- src/pytorch_tabular/tabular_datamodule.py
- src/pytorch_tabular/tabular_model.py
* Support Multi-GPU training
* Address some `FutureWarning` and `PerformanceWarning`
* Change type of `precision` to string to match PL
* Allow setting of `pickle_protocol` in `DataConfig` to save very large DataModules
* Preserve original index in `TabularDataset`
I've tested this using the DDP strategy but I believe it will work with other PL strategies as well.
----
📚 Documentation preview 📚: https://pytorch-tabular--517.org.readthedocs.build/en/517/
> Enable Support for Multi-GPU Training

- .github/workflows/testing.yml
This reduces the number of jobs per PR as it does not duplicate them and also cancels all outdated jobs per PR... as you can see right now the CI is completely sunken with just five open PRs
cc: @manujosephv 
----
📚 Documentation preview 📚: https://pytorch-tabular--524.org.readthedocs.build/en/524/
> chore(ci): setting concurrency

- src/pytorch_tabular/tabular_datamodule.py
- src/pytorch_tabular/utils/python_utils.py
Pytorch 2.6 updated the torch.load function with "weights_only = True" as default. 
This caused an issue with the library making any load process crash. This also caused the tests to fail for other PRs #540 and even other bot PRs, #536, #537. 
I set for all torch.load functions to be "weight_only = False" instead of the default True to fix this issue. 
----
📚 Documentation preview 📚: https://pytorch-tabular--543.org.readthedocs.build/en/543/
> Torch load issue fix with pytorch 2.6

- src/pytorch_tabular/tabular_datamodule.py
- src/pytorch_tabular/utils/python_utils.py
This PR fixes the torch.load() bug for pytorch versions < 2.6 from the PR #543. The test cases for older versions of Python and by extension PyTorch were failing cause of the new change. [see here](https://github.com/manujosephv/pytorch_tabular/actions/runs/14014540640/job/39238518649?pr=540)
What this PR updates?
Catches pytorch version and uses the correct syntax for torch.load() to use in 
tabular_datamodule.py and python_ultis.py
----
📚 Documentation preview 📚: https://pytorch-tabular--554.org.readthedocs.build/en/554/
> torch.load fix for all pytorch versions.

- src/pytorch_tabular/ssl_models/common/noise_generators.py
- src/pytorch_tabular/tabular_datamodule.py
numpy defaults to numpy.float64 when they should be numpy.float32
This caused training to fail on MPS devices but it works on my M1 with this.
----
📚 Documentation preview 📚: https://pytorch-tabular--540.org.readthedocs.build/en/540/
> Make tensor dtypes `np.float32` for MPS devices

- src/pytorch_tabular/tabular_model_tuner.py
It is not possible to access params through function signiture, the key should be metric_str
----
📚 Documentation preview 📚: https://pytorch-tabular--551.org.readthedocs.build/en/551/
> minor bug fix
